# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: kuy-api
# app and org for use with dashboard.serverless.com
app: kuycoin
org: kuycoin

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  profile: kuycoin
  logRetentionInDays: 30
  environment:
    Provider: "https://rpc.bitkubchain.io/"
    KuyAddress: "0x2009A60434dc8c8f772c9969d64868bDc2bF17B2"
    BurnAddress: "0x0000000000000000000000000000000000000000"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: arn:aws:lambda:${self:provider.region}:*:*
#    - Effect: Allow
#      Action:
#        - dynamodb:*
#      Resource: arn:aws:dynamodb:${self:provider.region}:*:*

functions:
  getTotalSupply:
    handler: handler.getTotalSupply
    events:
      - http:
          path: getTotalSupply
          method: get
          cors: true
  getCirculatingSupply:
    handler: handler.getCirculatingSupply
    events:
      - http:
          path: getCirculatingSupply
          method: get
          cors: true
  getTVL:
    handler: getTVL.getTVL
    events:
      - http:
          path: getTVL
          method: get
          cors: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
